### PR TITLE
refactor: decrease size admin-boundary files AB#8833

### PR DESCRIPTION
**Pull request by jannisvisser**

### CODE REVIEW

**Comment by gulfaraz** [comment]
@jannisvisser may I know what changed in these files? I'm unable to deduce what actually changed here.

**Comment by jannisvisser** [comment]
@gulfaraz see comment [here](https://dev.azure.com/redcrossnl/IBF%20System/_sprints/taskboard/IBF%20System%20Team/IBF%20System/IBF%20SWDEV/Sprint%2031?workitem=8833).

Very detailed boundaries (with a lot of corners) are being simplified. If you want to know more let's call.

**Comment by gulfaraz** [comment]
@jannisvisser [this clears it](https://dev.azure.com/redcrossnl/IBF%20System/_sprints/taskboard/IBF%20System%20Team/IBF%20System/IBF%20SWDEV/Sprint%2031?workitem=8833). Thank you!

**Review by gulfaraz — APPROVED** [review]
Seed script worked without issues.

```
Seed Disasters...
Seed Lead Times...
Seed Countries... UGA,ZMB,KEN,ETH,EGY,PHL
Seed Users...
Seed Areas of Focus...
Seed EAP Actions...
Seed Indicators...
Seed Layers...
Seed Admin Areas...
Seed Glofas Stations...
Seed Red Cross branches...
Skip Red Cross branches: KEN
Skip Red Cross branches: PHL
Seed Health Sites...
Seed Indicator data per admin-area...
Skip Indicator: Population - PHL
Seed rainfall data...
```

Zambia admin level 3 regions loaded on the dashboard as expected

Screenshot 2021-08-02 at 12 58 08

**Pull request merged**
