### PR TITLE
ci: run e2e and integration tests only when api-service or dashboard changes

### PR DESCRIPTION
**Pull request by gulfaraz**
## Describe your changes

The e2e and integration tests must only run when we change the dashboard or API-service.

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [ ] I have added tests wherever relevant
- [x] I have made sure that all automated checks pass before requesting a review

### CODE REVIEW

**Review by jannisvisser — APPROVED** [review]
looks good from code. If you can confirm that it works as expected functionally (runs if something changed, and not if nothing changed), then approved.

**Comment by jannisvisser** [comment]
@gulfaraz actually 1 more comment. The integration tests are not dependent on ibf-dashboard changes right. They only test backend api-calls.

**Review by jannisvisser — CHANGES_REQUESTED** [review]
see comment in PR

**Comment by gulfaraz** [comment]
@jannisvisser You are right. I've updated the workflow accordingly.

**Review by jannisvisser — APPROVED** [review]

**Pull request merged**
