### PR TITLE
Feat.api docs

### PR DESCRIPTION
**Pull request by gulfaraz**
This PR includes,
1. style changes to the docs
2. supporting text to help navigate the docs
3. hides the schemas at the bottom of the docs
4. example endpoint with its response documented
5. extra configuration options which are visible on the code side but maybe not on the UI

### CODE REVIEW

**Comment by gulfaraz** [comment]
@jannisvisser merging for sprint review

**Comment by jannisvisser** [comment]
@gulfaraz sure, but I still need to look at this I guess right?

**Comment by gulfaraz** [comment]
@jannisvisser yes

**Comment by jannisvisser** [comment]
@gulfaraz what is the 'example endpoint with its response documented' mentioned above? where do I see it in swagger / code?

**Comment by gulfaraz** [comment]
@jannisvisser it's the one referred in [DOCUMENTATION.md](https://github.com/rodekruis/IBF-system/blob/master/services/API-service/DOCUMENTATION.md)

**Pull request merged**
