### PR TITLE
fix: update zambia eap link AB#8207

### PR DESCRIPTION
**Pull request by gulfaraz**
Updated the EAP link for Zambia as per the comment in [AB#6090](https://dev.azure.com/redcrossnl/056030a3-96d2-4070-8718-48f602a2af75/_workitems/edit/6090)

### CODE REVIEW

**Comment by jannisvisser** [comment]
@gulfaraz is it correct and intended that this link requires credentials?

**Comment by gulfaraz** [comment]
> @gulfaraz is it correct and intended that this link requires credentials?

What do you mean it requires credentials? It's a direct download link that works on an incognito window.

**Comment by jannisvisser** [comment]
when I try this link (https://adore.ifrc.org/Download.aspx?FileId=35774), I get both in normal chrome and in incognito chrome a login-screen.

image

**Comment by gulfaraz** [comment]
@jannisvisser the url you shared appears to be incorrect

This is the correct url - https://adore.ifrc.org/Download.aspx?FileId=357745

The url in the commit
image

**Review by jannisvisser — APPROVED** [review]
ah weird.. copy/paste mistake, But approved then.

**Pull request merged**
