### PR TITLE
feat: add typhoon to PHL AB#10263

### PR DESCRIPTION
**Pull request by jannisvisser**

### CODE REVIEW

**Comment by SwatiTh** [comment]
Looks good up-till now.
Screenshot 2021-11-01 at 12 27 41

**Comment by jannisvisser** [comment]
@SwatiTh can you review one final time? Just set up everything, switch disasters for ETH and for PHL. Then I can merge.

**Comment by SwatiTh** [comment]
Looks Nice, 
however when we are switching from ethiopia to phillipines (using dunant id/pass).
it shows different admin levels for selected disaster.
Screenshot 2021-11-08 at 14 13 44

Screenshot 2021-11-08 at 14 16 43

-  for Dunant login scenarios 
Screenshot 2021-11-08 at 14 32 36

**Comment by jannisvisser** [comment]
@SwatiTh good comment. But that's part of the issue that the country-switch itself is not working properly (which we refined this morning). And furthermore, this is not a production-issue, as it's for dunant only. So I'm merging this one now then! Thanks.

**Pull request merged**
