### PR TITLE
fix: login email should support dot character AB#9307

### PR DESCRIPTION
**Pull request by gulfaraz**

### CODE REVIEW

**Comment by jannisvisser** [comment]
@SwatiTh can you review this one?

**Review by SwatiTh — COMMENTED** [review]
Looks good to me

**Comment by jannisvisser** [comment]
@gulfaraz is this change needed for ETH and/or ZWE users on production?

**Comment by gulfaraz** [comment]
@jannisvisser it's needed for ETH if we want abraham.tesfaye@redcrosseth.org to be able to login

**Pull request merged**
