### PR TITLE
Refactor.remove sql views

### PR DESCRIPTION
**Pull request by jannisvisser**

### CODE REVIEW

**Comment by jannisvisser** [comment]
@gulfaraz This is the big chunk of the 3/3 refactor item 6364 and could already be reviewed (and again would be handy to get out of the way, because it comes with lot of changes, which makes switching branches cumbersome). Remaining work can be considered separate.

**Comment by jannisvisser** [comment]
FYI: this reduces the nr. of schema's from 2 to 1. Only "IBF-app" is left (which could be renamed actually to "IBF" or something..).

**Review by gulfaraz — APPROVED** [review]
`npm run seed` runs without errors.

API-service gives the following error (occurs before pipeline has run),
```
[start:ibf-services  ] [start:ibf-api-service] [Nest] 10326   - 05/25/2021, 17:19:54   [ExceptionsHandler] Cannot read property 'date' of undefined +55ms
[start:ibf-services  ] [start:ibf-api-service] TypeError: Cannot read property 'date' of undefined
[start:ibf-services  ] [start:ibf-api-service]     at EventService.<anonymous> (/Users/gulfaraz/projects/justai/510.global/IBF/IBF-system/services/API-service/src/api/event/event.service.ts:121:19)
[start:ibf-services  ] [start:ibf-api-service]     at Generator.next (<anonymous>)
[start:ibf-services  ] [start:ibf-api-service]     at fulfilled (/Users/gulfaraz/projects/justai/510.global/IBF/IBF-system/services/API-service/src/api/event/event.service.ts:14:58)
[start:ibf-services  ] [start:ibf-api-service]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Running pipeline failed to download data for any country. Egypt takes forever so killed that one.

So I ran the pipeline in mock setting to review, and it worked!

Screenshot 2021-05-25 at 17 40 00

**Comment by jannisvisser** [comment]
@gulfaraz I have merged already and have created a task within this item still to remove the 3 within-endpoint-sql-queries you mention. Hopefully that still fits, otherwise we move them on.

**Pull request merged**
